### ISSUE TITLE
Le description n'est pas assez claire pour moi...

### ISSUE THREAD

**Issue by appgurueu** [MrChiantos/Minetest-SkinKey#3]
Je voulais savoir ce que votre projet fait. Pardon pour mon mauvaise francais, je suis allemand.

**Comment by MrChiantos** [comment]
Le Mod fournit une clé unique pour pouvoir utiliser cette même clé sur le script de site fournit, cela permet d'upload un skin avec la clé unique. Et après, quand le gérant redémarre son serveur, les joueurs ayant envoyer leur akin sur le site, peuvent l'utiliser en jeu. Chaques joueurs peut donc posséder son propre Avatar personnel et donc cela permet plus de choix qu'une liste de soins. Le site complet ou le script doit être néanmoins disponible sur celui qui héberge le serveur, cela permet d'avoir un service autonome de gestion de skin pour ses joueurs.

**Comment by appgurueu** [comment]
Ah ! Merci.
- LMD
